### ISSUE TITLE
No signal on raspberry pi zero

### ISSUE THREAD

**Issue by djogopatrao** [ArnoldUK/Faux86-remake#1]
I formatted a 2gb micro sd card  as fat32 and copied all files from the release 11-07-2023.

(btw windows defender accused a virus on faux86.exe but I just ignored)

the raspberry pi zero does not boot it. no led blink. the monitor is blank

It is plugged into my lg 34 ultrawide monitor and a 8bitdo joypad. this same setup worked with batocera.

**Comment by ArnoldUK** [comment]
The executable is built using outdated compiler so ignore defender warnings. There isn't a build for RPi zero and the Win32 build does not run on the ARM RPi builds. Only RPi 1-4 is supported at the moment. The RPi  zero would struggle to run this emulator anyway.
