### ISSUE TITLE
Release for 286 build

### ISSUE THREAD

**Issue by moononournation** [ArnoldUK/Faux86-remake#2]
Emulator Features claim implemented 286 instruction set. But the release build still at V20, is it possible release a 286 build?

**Comment by ArnoldUK** [comment]
Nothing in the pipeline for full 286 cpu instruction set emulation. Most of the 286 code are opcode tweaks to allow games and software for the 286 to run on a V20/8088 cpu. I will change the readme as that is not entirely correct.

**Comment by moononournation** [comment]
noted
